### ISSUE TITLE
术语表

### ISSUE THREAD

**Issue by QC-L** [docschina/rollupjs.org#10]
请大家把在翻译过程中遇到的生词在这里讨论。

## 术语对照

| 术语 | 译文 |
| :---: | :---: |
| live binding | 实时绑定 |

**Comment by parrotdance** [comment]
我先来一个:
live binding (暂译为 实时绑定)

群里同学的解释是: 当程序执行到那一行语句的时候，才开始做变量声明和值绑定，在执行之前不会有对代码预编译和预声明这些过程.
