### ISSUE TITLE
翻译任务认领

### ISSUE THREAD

**Issue by lcxfs1991** [docschina/rollupjs.org#2]
翻译前，请仔细阅读 [中文文档译文排版指南](https://github.com/reactjs/zh-hans.reactjs.org/wiki/React-%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97)。

## 任务认领说明

> 注意：一次尽量只认领一篇，给其他小伙伴留些机会~

从 Todo List 中选取未被人领取过的文章：

未被领取过：

* [ ] Home Page

领取过：

* [ ] Home Page (@QC-L)

领取过，已完成：

* [x] Home Page (@QC-L) #751 

**领取方式，在本 issues 下评论即可。**

认领任务格式：

```markdown
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Migrate |  To v4 from v3 | @QC-L  | 2020.06.14 - 2020.06.17
```

示例效果：

Section | Title | 译者 | 完成时间
-- | -- | -- | --
Migrate |  To v4 from v3 | @QC-L  | 2020.06.14 - 2020.06.17

## 任务认领列表

Todo List:

Guide

* [x] [Introduction](https://github.com/docschina/rollupjs.org/blob/cn/guide/zh/00-introduction.md) (@beetaa)
* [x] [Command Line Interface](https://github.com/docschina/rollupjs.org/blob/cn/guide/zh/01-command-line-reference.md) (@Jacksonlike)
* [x] [JavaScript API](https://github.com/docschina/rollupjs.org/blob/cn/guide/zh/02-javascript-api.md) (@CodingBuye)
* [x] [ES Module Syntax](https://github.com/docschina/rollupjs.org/blob/cn/guide/zh/03-es-module-syntax.md) (@phobal)
* [x] [Tutorial](https://github.com/docschina/rollupjs.org/blob/cn/guide/zh/04-tutorial.md) (@Catherine001li)
* [ ] [Plugin Development](https://github.com/docschina/rollupjs.org/blob/cn/guide/zh/05-plugin-development.md) 
* [x] [Frequently Asked Questions](https://github.com/docschina/rollupjs.org/blob/cn/guide/zh/06-faqs.md) (@parrotdance)
* [x] [Integrating Rollup With Other Tools](https://github.com/docschina/rollupjs.org/blob/cn/guide/zh/07-tools.md) (@wangxiaocuo)
* [x] [Troubleshooting](https://github.com/docschina/rollupjs.org/blob/cn/guide/zh/08-troubleshooting.md) (@pinpinye)
* [x] [Big list of options](https://github.com/docschina/rollupjs.org/blob/cn/guide/zh/999-big-list-of-options.md) (@whatwewant)

**Comment by Catherine001li** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guide |  Tutorial | @Catherine001li  | 2020.06.28 - 2020.07.05

**Comment by phobal** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guide | ES Module Syntax | @phobal | 2020.06.28 - 2020.07.03

**Comment by beetaa** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guide | Introduction | @beetaa | 2020.06.28 - 2020.07.01

**Comment by CodingBuye** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guide |  JavaScript API | @CodingBuye  | 2020.06.30 - 2020.07.03

**Comment by beetaa** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guide | Command Line Interface | @beetaa | 2020.06.28 - 2020.07.03

**Comment by zenghangyu** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guide| Plugin Development | @zenghy  | 2020.06.28 - 2020.07.03

**Comment by parrotdance** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guide |  Frequently Asked Questions | @parrotdance  | 2020.06.29 - 2020.06.30

**Comment by wangxiaocuo** [comment]
| Section | Title | 译者 | 完成时间 |
| --- | --- | --- | --- |
| Guide |  Integrating Rollup With Other Tools | @wangxiaocuo | 2020.06.29 - 2020.07.01 |

**Comment by pinpinye** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guide | troubleshooting | @pinpinye| 2020.07.04 - 2020.07.05

**Comment by Jacksonlike** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guide| Command Line Interface |@Jacskonlike | 2020.06.28 - 2020.07.03

**Comment by lcxfs1991** [comment]
> Section	Title	译者	完成时间
> Guide	Command Line Interface	@beetaa	2020.06.28 - 2020.07.03

这个分给 @Jacksonlike 翻译哈

**Comment by whatwewant** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guide | Big list of options | @whatwewant  | 2020.06.28 - 2020.07.05

**Comment by guimeisang** [comment]
Big list of options 我认领下

**Comment by Eric-art-coder** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guide | Big list of options | @guimeisang | 2020.06.28 - 2020.07.03

**Comment by lcxfs1991** [comment]
> Section	Title	译者	完成时间
> Guide	Big list of options	@guimeisang	2020.06.28 - 2020.07.03

这个已经被人认领啦。后续我们还会放出更多的翻译任务。感谢你的支持！

**Comment by beetaa** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guide | Plugin Development | @beetaa | 2020.06.30 - 2020.07.02

**Comment by Catherine001li** [comment]
您的来件已收到，谢谢!
